export const labels = {
    modalTitle: 'フリーデスク予約',
    close: '閉じる',
    closeSymbol: '×',
    tabReservation: '予約',
    tabAdmin: '管理',
    loading: '読み込み中...',
    updating: '更新中...',
    noData: 'データがありません。',
    confirm: '確認',
    cancel: 'キャンセル',
    ok: 'OK',
    deskLabel: 'デスク:',
    dateLabel: '日付:',
    reserverLabel: '予約者:',
    name: '名称',
    sortOrder: '表示順',
    status: '状態',
    actions: '操作',
    active: '有効',
    inactive: '無効',
    edit: '編集',
    delete: '削除',
    add: '追加',
    update: '更新',
    deskAdd: 'デスク追加',
    deskEdit: 'デスク編集',
    dateHeader: '日付',
    yearSuffix: '年',
    monthSuffix: '月',
    prevMonth: '← 前月',
    nextMonth: '翌月 →',
    emptySlot: '—',
    available: '空き',
};
